services:
  api:
    build:
      context: ./DeviceMonitoringAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
     - ASPNETCORE_URLS=http://+:80
    networks:
      - monitoring-net

  spa:
    build:
      context: ./DeviceMonitoring.Spa
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge